

learn from https://zhuanlan.zhihu.com/p/25572330

In [ ]:
# from __future__ import print_function
import torch
import numpy as np

# Tensors

In [4]:
x = torch.Tensor(5, 3)  # 构造一个未初始化的5*3的矩阵
x = torch.rand(5, 3)  # 构造一个随机初始化的矩阵
x # 此处在notebook中输出x的值来查看具体的x内容

tensor([[0.4643, 0.0113, 0.9599],
        [0.8304, 0.6745, 0.7752],
        [0.6968, 0.7879, 0.8269],
        [0.2326, 0.4592, 0.8652],
        [0.0587, 0.3681, 0.1578]])

In [5]:
x.size()
#NOTE: torch.Size 事实上是一个tuple, 所以其支持相关的操作*

torch.Size([5, 3])

In [7]:
y = torch.rand(5, 3)
#此处 将两个同形矩阵相加有两种语法结构
x + y # 语法一
torch.add(x, y) # 语法二

tensor([[0.5130, 0.0480, 1.9584],
        [1.5444, 0.9801, 1.4787],
        [1.0601, 1.5573, 1.8073],
        [0.8055, 1.2116, 1.0933],
        [0.4299, 0.5034, 0.9928]])

In [8]:
# 另外输出tensor也有两种写法
result = torch.Tensor(5, 3) # 语法一
torch.add(x, y, out=result) # 语法二
y.add_(x) # 将y与x相加

tensor([[0.5130, 0.0480, 1.9584],
        [1.5444, 0.9801, 1.4787],
        [1.0601, 1.5573, 1.8073],
        [0.8055, 1.2116, 1.0933],
        [0.4299, 0.5034, 0.9928]])

In [9]:
# 特别注明：任何可以改变tensor内容的操作都会在方法名后加一个下划线'_'
# 例如：x.copy_(y), x.t_(), 这俩都会改变x的值。

#另外python中的切片操作也是资次的。
x[:,1] #这一操作会输出x矩阵的第二列的所有值

tensor([0.0113, 0.6745, 0.7879, 0.4592, 0.3681])

# Numpy桥

In [ ]:
# 此处演示tensor和numpy数据结构的相互转换
a = torch.ones(5)
b = a.numpy()

# 此处演示当修改numpy数组之后,与之相关联的tensor也会相应的被修改
a.add_(1)
print("a", a)
print("b", b)

# 将numpy的Array转换为torch的Tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

# 另外除了CharTensor之外，所有的tensor都可以在CPU运算和GPU预算之间相互转换
# 使用CUDA函数来将Tensor移动到GPU上
# 当CUDA可用时会进行GPU的运算
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y